language: java
jdk:
- oraclejdk8
script:
- mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: JLAUavkGDr/prdrHAvZDYu3WSuS2Ds9dboR7EPCuukNhI7eCjwLqkr4UZwCx6p1J/fy+a3RzOFhVVGx1HVuog9dk42oyGIw21MwNrTtk20nxaTUKZKyLKbXoXNuPZ31bOGcvYVefr+vswM5rmBxyT9x0s7d08LiQj7Ui3ZQGOsFINLaL0UIWk+k2TqD9kvGoooQ/2LUZvzT9OnK8X9TwK5GQhMhhsFur3HWI7iTfonDlcjJqahXYOSScXl1oluS/mhc3wLmdsnP8ca9ONxybj72gWpfxF1UBoeShrTeADLcLnUzTzWPPPoihXgsxYNC0RJQ47LaFZkzDEmudH1EKOct8t9tM0RqNPzuAYAcKXQwRMLTFzGfTRH9NGGWu4VaT0s+SBOY2xarDySPT5Fk+E2/BWCAZU0imQoMSD13w0xd6t6mn6hRcu/HsG2/s4xTA/i6c7wyTeAS2WqNkeZliFdKoPYT9YvRWKVS3sQCflIKozez7Ru3SOkqZGShHkwRVRCYz53UdambLZDxMSolLytG/c+ZcQ9DP/MrI+XOKVfoV1+z3C/W5P4TRpj+cq5jGCqSR3XsWp+ov1VwgPzsfsuOtolwrhfjyueHczZqtuPhbuZS+PlDTGK2/8YcEGUGnoNt/HLyP1rNRQrhZuf3S9tsVBpT72oYPYD5MTUpkmbc=
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    tags: true
